export const CREATE_CONTACT = "CREATE_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const GET_CONTACT = "GET_CONTACT";
export const DELETE_ALL_USER = "DELETE_ALL_USER";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
